name: Fabletics Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        type: choice
        options:
          - production
          - preview
          - qa

jobs:
  test-us:
    uses: ./.github/workflows/base.yml
    with:
      brand: fabletics
      domains: us
      environment: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || 'production' }}
    secrets: inherit

  test-uk:
    uses: ./.github/workflows/base.yml
    with:
      brand: fabletics
      domains: uk
      environment: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || 'production' }}
    secrets: inherit

  test-ca:
    uses: ./.github/workflows/base.yml
    with:
      brand: fabletics
      domains: ca
      environment: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || 'production' }}
    secrets: inherit

  test-de:
    uses: ./.github/workflows/base.yml
    with:
      brand: fabletics
      domains: de
      environment: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || 'production' }}
    secrets: inherit

  test-fr:
    uses: ./.github/workflows/base.yml
    with:
      brand: fabletics
      domains: fr
      environment: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || 'production' }}
    secrets: inherit

  test-es:
    uses: ./.github/workflows/base.yml
    with:
      brand: fabletics
      domains: es
      environment: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || 'production' }}
    secrets: inherit

  test-nl:
    uses: ./.github/workflows/base.yml
    with:
      brand: fabletics
      domains: nl
      environment: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || 'production' }}
    secrets: inherit

  test-sw:
    uses: ./.github/workflows/base.yml
    with:
      brand: fabletics
      domains: sw
      environment: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || 'production' }}
    secrets: inherit 