name: SavageX Tests
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        type: choice
        options:
          - production
          - preview
          - qa

jobs:
  test-us:
    uses: ./.github/workflows/base.yml
    with:
      brand: savagex
      domain: us
      environment: ${{ github.event.inputs.environment }}

  test-uk:
    uses: ./.github/workflows/base.yml
    with:
      brand: savagex
      domain: uk
      environment: ${{ github.event.inputs.environment }}

  test-ca:
    uses: ./.github/workflows/base.yml
    with:
      brand: savagex
      domain: ca
      environment: ${{ github.event.inputs.environment }}

  test-de:
    uses: ./.github/workflows/base.yml
    with:
      brand: savagex
      domain: de
      environment: ${{ github.event.inputs.environment }}

  test-fr:
    uses: ./.github/workflows/base.yml
    with:
      brand: savagex
      domain: fr
      environment: ${{ github.event.inputs.environment }}

  test-es:
    uses: ./.github/workflows/base.yml
    with:
      brand: savagex
      domain: es
      environment: ${{ github.event.inputs.environment }} 