name: Yitty Tests
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        type: choice
        options:
          - production
          - preview
          - qa

jobs:
  test-us:
    uses: ./.github/workflows/base.yml
    with:
      brand: yitty
      domain: us
      environment: ${{ github.event.inputs.environment }}
    secrets: inherit

  test-uk:
    uses: ./.github/workflows/base.yml
    with:
      brand: yitty
      domain: uk
      environment: ${{ github.event.inputs.environment }}
    secrets: inherit 