name: Yitty Tests
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        type: choice
        options:
          - production
          - preview
          - qa
      domain:
        description: 'Select domain'
        required: true
        type: choice
        options:
          - all
          - us

jobs:
  test-us:
    if: github.event.inputs.domain == 'us' || github.event.inputs.domain == 'all'
    uses: ./.github/workflows/base.yml
    with:
      brand: yitty
      domain: us
      environment: ${{ github.event.inputs.environment }}
    secrets: inherit

  test-uk:
    if: github.event.inputs.domain == 'uk' || github.event.inputs.domain == 'all'
    uses: ./.github/workflows/base.yml
    with:
      brand: yitty
      domain: uk
      environment: ${{ github.event.inputs.environment }}
    secrets: inherit 